**NIVASRI T  | 24BAD081**

In [2]:

# TASK 1
# Single Layer Perceptron
# AND & OR Logic Gates

import numpy as np

# Perceptron Class
class Perceptron:

    def __init__(self, learning_rate=0.1, epochs=20):
        self.lr = learning_rate
        self.epochs = epochs

    def activation(self, x):
        if x >= 0:
            return 1
        else:
            return 0

    def fit(self, X, y):

        self.weights = np.zeros(X.shape[1])
        self.bias = 0

        for epoch in range(self.epochs):

            for i in range(len(X)):

                linear_output = np.dot(X[i], self.weights) + self.bias
                prediction = self.activation(linear_output)

                error = y[i] - prediction

                self.weights += self.lr * error * X[i]
                self.bias += self.lr * error

    def predict(self, X):

        predictions = []

        for x in X:
            linear_output = np.dot(x, self.weights) + self.bias
            predictions.append(self.activation(linear_output))

        return np.array(predictions)

# Accuracy Function
def accuracy(y_true, y_pred):
    return np.mean(y_true == y_pred) * 100


# AND Gate

print("=========== AND GATE ===========")

X_and = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

y_and = np.array([0,0,0,1])

# Increased epochs improves accuracy
model_and = Perceptron(learning_rate=0.1, epochs=50)

model_and.fit(X_and, y_and)

pred_and = model_and.predict(X_and)

print("\nPredictions:")
print(pred_and)

print("\nActual:")
print(y_and)

print("\nAccuracy:", accuracy(y_and, pred_and), "%")


# OR Gate

print("\n=========== OR GATE ===========")

X_or = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

y_or = np.array([0,1,1,1])

model_or = Perceptron(learning_rate=0.1, epochs=50)

model_or.fit(X_or, y_or)

pred_or = model_or.predict(X_or)

print("\nPredictions:")
print(pred_or)

print("\nActual:")
print(y_or)

print("\nAccuracy:", accuracy(y_or, pred_or), "%")

=========== AND GATE ===========

Predictions:
[0 0 0 1]

Actual:
[0 0 0 1]

Accuracy: 100.0 %

=========== OR GATE ===========

Predictions:
[0 1 1 1]

Actual:
[0 1 1 1]

Accuracy: 100.0 %
